### ISSUE TITLE
Comment/Feature suggestion: location of downloaded models

### ISSUE THREAD

**Issue by stephantual** [Fannovel16/comfyui_controlnet_aux#189]
Hello! Thank you for this 💯 set of nodes.
Question: why are the models specifically placed in :

`ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\`

... while convenient (as they go into their own directories and I imaging you have an auto-check on updates), I'm curious why they don't go into the usual 'models/xxxx' folder of confy ui, as comfy then fails to recognize them as 'installed' (i think it sniffes only where told to by the yaml files.

It's not a biggy, and i love the auto-download, i'm just very curious why this was done this way, as it can lead to duplicated models, and in turn, confusion as to which one is the 'latest' (given that their creation date is the download date on win11 at least)

Thank you.

**Comment by Layer-norm** [comment]
In fact, you can customize the model root path through the **config.yaml**, and even outside the ComfyUI folder. This feature is actually a compromise made to accommodate older versions and other requirements. Because everyone's paths can be different (especially when models are placed outside the comfyui folder), managing them using ComyUI-manager's model-list might be somewhat challenging currently. 

Moreover, preprocessor models are not files that require updates. New models will use different names to distinguish them from older ones, so it's just a matter of presence or absence.

Do you have some suggestions? Perhaps there's a solution that could make better.

**Comment by Fannovel16** [comment]
> I'm curious why they don't go into the usual 'models/xxxx' folder of confy ui

Checkpoint files of preprocessors are constant assets files. The reason is that majority of AI papers don't have community's finetune, which also apply to preprocessors. Only some exception I know are generative and detection models

**Comment by stephantual** [comment]
Thank you - this makes sense. I was just making sure that comfy manager is 'aware' of the presence of such models so they don't get duped (even if they do, I won't lose sleep over it ;) - thank you to both of you! closing.
