### ISSUE TITLE
MeshGraphormer Hand Refiner: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by DutchEllie** [Fannovel16/comfyui_controlnet_aux#218]
Hello, I ran into this issue today when trying to use the MeshGraphormer. 

I use ComfyUI on Linux with an AMD RX 7900 XTX. I run Comfy in a Python virtualenv that runs Python 3.11.6. 

My workflow looks like this:
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/6501187/847eecc4-6489-46c0-abd4-fe80cef0c8b2)

The error occurs when the node tries to run. In the log it first downloaded the models, but it happens too after they have already downloaded.
This is the log of the terminal when it happens:
```
Failed to find /home/user/bighome/Software/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/ControlNet-HandRefiner-pruned/hrnetv2_w64_imagenet_pretrained.pth.
 Downloading from huggingface.co
hrnetv2_w64_imagenet_pretrained.pth: 100%|███████████████████████████| 513M/513M [00:04<00:00, 114MB/s]
Failed to find /home/user/bighome/Software/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/ControlNet-HandRefiner-pruned/graphormer_hand_state_dict.bin.
 Downloading from huggingface.co
graphormer_hand_state_dict.bin: 100%|████████████████████████████████| 856M/856M [00:07<00:00, 112MB/s]
set os.environ[OMP_NUM_THREADS] to 4
/usr/lib/python3.11/site-packages/scipy/sparse/_index.py:102: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
=> loading pretrained model /home/user/bighome/Software/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/ControlNet-HandRefiner-pruned/hrnetv2_w64_imagenet_pretrained.pth
./start.sh: line 3: 172853 Segmentation fault      (core dumped) python main.py --temp-directory /tmp/comfy
```

I have updated ComfyUI, updated all nodes including this one. I also renewed my pyenv virtualenv and installed all dependencies, including the ones like onnxruntime-gpu and the ones in the requirements.txt of this custom node.

**Comment by permaloom** [comment]
I have the same issue with a similar setup.

Running on Fedora 39 with an AMD RX 6750 XT using the kernel `amdgpu` driver, I've created Python virtual environments with Python versions 3.10.13 and 3.11.7 and installed all dependencies for both ComfyUI and ControlNet Auxiliary Preprocessors. I am using ROCm 5.7 nightly (cannot use 5.6 due to PCIe atomics). Both environments experience a segmentation fault during/after the "loading pretrained model" step, matching the log already posted.

Here is the relevant output of `dmesg`:
[dmesg.txt](https://github.com/Fannovel16/comfyui_controlnet_aux/files/14087105/dmesg.txt)

**Comment by permaloom** [comment]
After fully updating my system and ComfyUI, the crash seems to be fixed as I can no longer reproduce it. The MeshGraphormer Hand Refiner is now working as expected for me.

**Comment by DutchEllie** [comment]
Same here, I updated everything and now the hand refiner seems to work fine. I'll close the issue as my problem has been solved.
