### ISSUE TITLE
matplotlib 

### ISSUE THREAD

**Issue by liujintiger** [Fannovel16/comfyui_controlnet_aux#421]
[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module dwpose because ModuleNotFoundError: No module named 'matplotlib'
        Failed to import module pose_keypoint_postprocess because ModuleNotFoundError: No module named 'matplotlib'

**Comment by FugueSegue** [comment]
I am having the same problem and it is VERY frustrating. I use the ComfyUI portable. This is probably a very important point. I see in other posts about this exact same issue that the solution is to manually install matplotlib:

`pip install matplotlib`

For me, this DOES NOT WORK. It is probably because I don't know exactly what I'm doing. This command installs matplotlib to my Windows install of Python. I don't think it has any effect on the Python that's installed with the portable version of ComfyUI.

My ComfyUI installation is portable. Doesn't it use something like venv? If so, I need the exact, precise procedure of commands to do this manual install with this portable version. Don't assume that I know how to pip install anything with the portable ComfyUI.

I've been trying all morning to get this custom node to install without error. I've done a completely fresh install of ComfyUI portable. I'm certain that it is the latest version. I've only installed the Manager custom node and I've been trying to install comfyui_controlnet_aux custom node using the Manager. I am always getting an error with matplotlib.

Please advise.

**Comment by realxipen** [comment]
having the same issue. tried uninstalling and reinstalling

**Comment by vlrevolution** [comment]
having same issue, installing it doesn't work

**Comment by robinjhuang** [comment]
Can we just add `matplotlib` to the requirements.txt?
