### ISSUE TITLE
Is it possible to add a configuration that specifies the path to the preprocessing model?

### ISSUE THREAD

**Issue by petercham** [Fannovel16/comfyui_controlnet_aux#68]
It would be nice if it could be added to ComfyUI's extended search path!

**Comment by cbw7172002** [comment]
同问，怎么配置 老是错误

(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/body_pose_model.pth (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000275D345CAF0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: bcf7676b-beae-4a29-8cdd-c87986200dd6)')' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth
WARNING:huggingface_hub.utils._http:'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/body_pose_model.pth (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000275D345CAF0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: bcf7676b-beae-4a29-8cdd-c87986200dd6)')' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/body_pose_model.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\openpose.py", line 27, in estimate_pose
    model = OpenposeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\open_pose\__init__.py", line 134, in from_pretrained
    body_model_path = hf_hub_download(pretrained_model_or_path, filename, cache_dir=cache_dir)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\file_download.py", line 1291, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by Fannovel16** [comment]
@petercham @cbw7172002 Set `annotator_ckpts_path` in https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/config.yaml to the path. 

It is recommended to use absolute path if you replace the default value. Also if you are using Windows, use double backslashes instead of single one. For example, if you want to save preprocessing models to `E:\AI-Folder\controlnet_prep_ckpts`, write
```
annotator_ckpts_path: "E:\\AI-Folder\\controlnet_prep_ckpts"
```
