### ISSUE TITLE
Depth map preprocessor failed (depth预处理失败！)

### ISSUE THREAD

**Issue by wgb0451** [Fannovel16/comfyui_controlnet_aux#77]
下载了zoe模型后就报出错误，其他模型预处理没问题。

**Comment by Fannovel16** [comment]
> After downloading the zoe model, an error was reported, but other model preprocessing was fine.

Try re-downloading it. If the error still exist, post the log of the command-line

DeepL: 尝试重新下载。如果错误仍然存在，请张贴命令行日志

**Comment by notfood** [comment]
I've been getting the same error for about a week now. Tried re-downloading everything, tried clearing the venv and installing it again with no success. It's only Zoe Depth Preprocessor.
![workflow](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/5370107/6584682f-b9d1-4863-ac7f-4ce51f8b90dd)
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py", line 17, in execute
    model = ZoeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/__init__.py", line 30, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
  File "/media/Hakugyokurou/home/Projects/AI/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ZoeDepth:
        Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index". 

Prompt executed in 3.13 seconds
```

**Comment by Franks001** [comment]
I have encountered the same problem, with detailed information as follows:** ComfyUI start up time: 2023-10-19 10:47:51.285708

Prestartup times for custom nodes:
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32725 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Adding extra search path checkpoints E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/Stable-diffusion
Adding extra search path configs E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/Stable-diffusion
Adding extra search path vae E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/VAE
Adding extra search path loras E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/Lora
Adding extra search path loras E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/LyCORIS
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/ESRGAN
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/RealESRGAN
Adding extra search path upscale_models E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/SwinIR
Adding extra search path embeddings E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\embeddings
Adding extra search path hypernetworks E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/hypernetworks
Adding extra search path controlnet E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/ControlNet
Adding extra search path controlnet E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\extensions\sd-webui-controlnet\models
Adding extra search path mmdets E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/mmdets/bbox
Adding extra search path ultralytics E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models\ultralytics\bbox
Adding extra search path ultralytics E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models\ultralytics\segm
Adding extra search path sams E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models/sams
Adding extra search path seecoders E:\AI\SD\webui\QiuYe\sd-webui-aki-v4.3\models\seecoders
[Allor]: 0 standard nodes was overridden.
[Allor]: 12 modules enabled.
[Allor]: 95 nodes was loaded.
### Loading: ComfyUI-Impact-Pack (V4.25)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.32)
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1590 [0d45a565] | Released on '2023-10-18'
### Loading: ComfyUI-Workflow-Component (V0.43.2) !! WARN: This is an experimental extension. Extremely unstable. !!
Registered sys.path: ['E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\Lib\\site-packages\\git\\ext\\gitdb', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\comfy', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\python311.zip', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\Lib\\site-packages', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\Lib\\site-packages\\win32', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\Lib\\site-packages\\win32\\lib', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\python_embeded\\Lib\\site-packages\\Pythonwin', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..', 'E:\\AI\\SD\\ComfyUI\\portable\\cu121\\ComfyUI\\custom_nodes\\ComfyUI-Workflow-Component']
E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
web\extensions\BaiduTranslatePreview.js
custom_nodes\ComfyUI_Prompt_Translate_to_English\js\BaiduTranslatePreview.js
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it yourself.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: C:\Users\Administrator\AppData\Local\Programs\Python\ffmpeg-5.1.2-essentials_build\bin
WAS Node Suite: Finished. Loaded 196 nodes successfully.

	"The distance between insanity and genius is measured only by success." - Bruce Feirstein

Import times for custom nodes:
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ksampler_sdxl.py
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfy_translation_node
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUi_PromptStylers
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_SeeCoder
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\SDXL Mile High Prompt Styler
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Workflow-Component
   0.1 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI_Prompt_Translate_to_English
   0.3 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-CLIPSeg
   0.4 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes
   0.6 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Allor
   1.4 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.3 seconds: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002845F6FBBD0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 2c11f7da-11c4-4dc0-8afd-3f602ea53f5a)')' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/ZoeD_M12_N.pt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\zoe.py", line 18, in execute
    out = common_annotator_call(model, image, resolution=resolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 46, in common_annotator_call
    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\__init__.py", line 49, in __call__
    depth = self.model.infer(image_depth)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 126, in infer
    return self.infer_with_flip_aug(x, pad_input=pad_input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 110, in infer_with_flip_aug
    out = self._infer_with_pad_aug(x, pad_input=pad_input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 88, in _infer_with_pad_aug
    out = self._infer(x)
          ^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\depth_model.py", line 55, in _infer
    return self(x)['metric_depth']
           ^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\zoedepth\zoedepth_v1.py", line 144, in forward
    rel_depth, out = self.core(x, denorm=denorm, return_rel_depth=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 265, in forward
    x = self.prep(x)
        ^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 189, in __call__
    return self.normalization(self.resizer(x))
                              ^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\zoe\zoedepth\models\base_models\midas.py", line 176, in __call__
    return nn.functional.interpolate(x, (height, width), mode='bilinear', align_corners=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\SD\ComfyUI\portable\cu121\python_embeded\Lib\site-packages\torch\nn\functional.py", line 3924, in interpolate
    raise TypeError(
TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [<class 'numpy.int32'>, <class 'numpy.int32'>]
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

Prompt executed in 15.20 seconds

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/d67fe4c44e5b035ed68ed0d481b8b0ebf4bad41f
